ALTER TABLE "Account" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "Transaction" ADD COLUMN "assignedMemberId" TEXT;
ALTER TABLE "Transfer" ADD COLUMN "assignedMemberId" TEXT;
ALTER TABLE "Investment" ADD COLUMN "assignedMemberId" TEXT;
ALTER TABLE "TelegramChannel" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "TelegramBotIntegration" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "TelegramUserAccountIntegration" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "Promo" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "AdvertisingSource" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "AdCampaign" ADD COLUMN "assignedMemberId" TEXT;
ALTER TABLE "AdHypothesis" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "TelegramChannelNetwork" ADD COLUMN "assignedMemberId" TEXT, ADD COLUMN "createdByUserId" TEXT;

ALTER TABLE "Account" ADD CONSTRAINT "Account_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Transfer" ADD CONSTRAINT "Transfer_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Transfer" ADD CONSTRAINT "Transfer_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Investment" ADD CONSTRAINT "Investment_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Investment" ADD CONSTRAINT "Investment_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramChannel" ADD CONSTRAINT "TelegramChannel_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramChannel" ADD CONSTRAINT "TelegramChannel_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramBotIntegration" ADD CONSTRAINT "TelegramBotIntegration_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramBotIntegration" ADD CONSTRAINT "TelegramBotIntegration_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramUserAccountIntegration" ADD CONSTRAINT "TelegramUserAccountIntegration_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramUserAccountIntegration" ADD CONSTRAINT "TelegramUserAccountIntegration_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Promo" ADD CONSTRAINT "Promo_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Promo" ADD CONSTRAINT "Promo_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdvertisingSource" ADD CONSTRAINT "AdvertisingSource_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdvertisingSource" ADD CONSTRAINT "AdvertisingSource_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdCampaign" ADD CONSTRAINT "AdCampaign_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdCampaign" ADD CONSTRAINT "AdCampaign_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdHypothesis" ADD CONSTRAINT "AdHypothesis_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdHypothesis" ADD CONSTRAINT "AdHypothesis_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramChannelNetwork" ADD CONSTRAINT "TelegramChannelNetwork_assignedMemberId_fkey" FOREIGN KEY ("assignedMemberId") REFERENCES "WorkspaceMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TelegramChannelNetwork" ADD CONSTRAINT "TelegramChannelNetwork_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "Account_workspaceId_assignedMemberId_idx" ON "Account"("workspaceId", "assignedMemberId");
CREATE INDEX "Transaction_workspaceId_assignedMemberId_idx" ON "Transaction"("workspaceId", "assignedMemberId");
CREATE INDEX "Transfer_workspaceId_assignedMemberId_idx" ON "Transfer"("workspaceId", "assignedMemberId");
CREATE INDEX "Investment_workspaceId_assignedMemberId_idx" ON "Investment"("workspaceId", "assignedMemberId");
CREATE INDEX "TelegramChannel_workspaceId_assignedMemberId_idx" ON "TelegramChannel"("workspaceId", "assignedMemberId");
CREATE INDEX "TelegramBotIntegration_workspaceId_assignedMemberId_idx" ON "TelegramBotIntegration"("workspaceId", "assignedMemberId");
CREATE INDEX "TelegramUserAccountIntegration_workspaceId_assignedMemberId_idx" ON "TelegramUserAccountIntegration"("workspaceId", "assignedMemberId");
CREATE INDEX "Promo_workspaceId_assignedMemberId_idx" ON "Promo"("workspaceId", "assignedMemberId");
CREATE INDEX "AdvertisingSource_workspaceId_assignedMemberId_idx" ON "AdvertisingSource"("workspaceId", "assignedMemberId");
CREATE INDEX "AdCampaign_workspaceId_assignedMemberId_idx" ON "AdCampaign"("workspaceId", "assignedMemberId");
CREATE INDEX "AdHypothesis_workspaceId_assignedMemberId_idx" ON "AdHypothesis"("workspaceId", "assignedMemberId");
CREATE INDEX "TelegramChannelNetwork_workspaceId_assignedMemberId_idx" ON "TelegramChannelNetwork"("workspaceId", "assignedMemberId");
