import type { Currency, Icon, ResolvedEmoji } from "./core";
import type { TransactionType } from "./finance";
import type { AdCampaign } from "./ad-campaigns";

export type DashboardSummary = {
  period: { dateFrom: string; dateTo: string };
  totalBalancePrimary: number;
  totalBalanceSecondary: number;
  primaryCurrency?: Currency;
  secondaryCurrency?: Currency;
  incomeForPeriod: number;
  expensesForPeriod: number;
  profitForPeriod: number;
  investedCapital: number;
  investedCapitalForPeriod: number;
  operatingProfitAllTime: number;
  remainingToBreakEven: number;
  projectedMonthlyProfit: number;
  projectedPaybackMonths: number | null;
  revenueTransactionsCount: number;
  channelsWithRevenueCount: number;
  adSpendForPeriod: number;
  totalJoinedFromAds: number;
  averageCPA: number | null;
  campaignsCount: number;
  periodCampaignsCount: number;
  telegramChannelsCount: number;
  ownChannelsCount: number;
  externalChannelsCount: number;
  workspaceMembersCount: number;
  totalSubscribers: number;
  activeSubscribersEstimate: number;
  anomalousChannelsCount: number;
  dailyTrend: Array<{
    date: string;
    income: number;
    expenses: number;
    profit: number;
    investments: number;
    cumulativeProfitAfterInvestments: number;
    adSpend: number;
    joined: number;
  }>;
  categoryBreakdown: Array<{
    id?: string | null;
    name: string;
    type: TransactionType;
    amount: number;
    count: number;
    iconId?: string | null;
    icon?: Icon | null;
    iconPresentation?: ResolvedEmoji | null;
  }>;
  accountBalances: Array<{
    id: string;
    name: string;
    currency: Currency;
    iconId?: string | null;
    icon?: Icon | null;
    iconPresentation?: ResolvedEmoji | null;
    balance: number;
    primary: number;
    secondary: number;
  }>;
  channelPerformance: Array<{
    id: string;
    title: string;
    username?: string | null;
    photoUrl?: string | null;
    revenue: number;
    allTimeRevenue: number;
    spend: number;
    acquisitionCost: number;
    net: number;
    remainingToBreakEven: number;
    projectedPaybackMonths: number | null;
    joined: number;
    campaigns: number;
    cpa: number | null;
  }>;
  topOwnChannels: Array<{
    id: string;
    title: string;
    username?: string | null;
    photoUrl?: string | null;
    subscribers: number;
    activeSubscribers: number;
    viewRate?: number | null;
    dataQuality?: string | null;
  }>;
  campaignStatusCounts: Record<string, number>;
  adQualityCounts: Record<string, number>;
  hypothesisStatusCounts: Record<string, number>;
  bestCampaigns: AdCampaign[];
  worstCampaigns: AdCampaign[];
};
